# Generated by Django 3.2.5 on 2022-08-22 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_bookview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookview',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
