# Generated by Django 3.2.5 on 2022-09-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_order_order_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_receiver',
            field=models.CharField(max_length=100),
        ),
    ]
