# Generated by Django 3.2.5 on 2022-09-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_order_phone_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='book',
            field=models.IntegerField(),
        ),
    ]
