# Generated by Django 3.2.5 on 2022-09-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_order_detail_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
