# Generated by Django 3.2.5 on 2022-09-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='books.Tag'),
        ),
    ]
