# Generated by Django 3.2.5 on 2022-09-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20220925_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='name',
            field=models.TextField(default='12'),
            preserve_default=False,
        ),
    ]
