# Generated by Django 3.2.5 on 2022-10-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_book_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ImageField(default=None, upload_to='author/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_image',
            field=models.ImageField(default=None, upload_to='company/%Y/%m'),
        ),
    ]
